apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-gjxw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-gjxw
    app.kubernetes.io/part-of: integ-app-bgna
  name: hacbs-test-project-gjxw
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-gjxw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-gjxw
    spec:
      containers:
      - image: quay.io/kasem_org/integration1-kcao-tenant/integ-app-bgna/hacbs-test-project-gjxw@sha256:7097db0d70ddab0d990264cd32d2eada9d473a43e1f26bd73b0474d1553f3b9e
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
